import { useState, type ChangeEvent, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { analyzeTrendCsv } from '../lib/api';
import type { SiteLang, TrendCandle, TrendPayload } from '../types';

const TREND_TOOL_SLUG = 'trend-analyzer';
const TREND_FETCHER_REPO_URL = 'https://github.com/garmlegarmle/ga-ml-trend-fetcher';
const TREND_FETCHER_MAC_URL = `${TREND_FETCHER_REPO_URL}/releases/latest/download/GA-ML-TrendFetcher-macos.zip`;
const TREND_FETCHER_WINDOWS_URL = `${TREND_FETCHER_REPO_URL}/releases/latest/download/GA-ML-TrendFetcher-windows.zip`;

const TOOL_COPY = {
  en: {
    featureEyebrow: 'Built-in Tool',
    featureTitle: 'Trend Analyzer',
    featureDescription:
      'Upload an analysis-ready OHLCV CSV, then review the latest 200 daily candles, indicator lines, and current trend readout.',
    featureCta: 'Open tool',
    eyebrow: 'Tool / Market Trend',
    title: 'Trend Analyzer',
    description:
      'Upload a daily OHLCV CSV generated by the desktop downloader. The file is analyzed once on the server, returned as a chart payload, and discarded immediately.',
    tickerLabel: 'Ticker override',
    tickerPlaceholder: 'Optional if the CSV file name already includes the ticker',
    fileLabel: 'OHLCV CSV file',
    fileButton: 'Choose CSV',
    fileEmpty: 'No file selected',
    submit: 'Analyze CSV',
    processing: 'Analyzing...',
    privacyNotice: 'Uploaded CSV files are processed once and removed immediately. We do not keep them in the database.',
    downloadTitle: 'Desktop downloader',
    downloadBody: 'Use the standalone desktop app to fetch local CSV files, then upload them here for analysis.',
    macDownload: 'macOS app',
    windowsDownload: 'Windows app',
    repoLink: 'Source repo',
    csvTitle: 'Expected CSV columns',
    csvBody: 'Required: date, open, high, low, close, volume. Recommended: symbol, adj_close.',
    csvHint: 'For a 200-session chart and warm-up indicators, the desktop downloader should export roughly the latest 260 trading bars.',
    activeTicker: 'Selected ticker',
    fileStatus: 'Current file',
    asOf: 'As of',
    window: 'Window',
    chartTitle: 'Daily Candles',
    chartSubtitle: 'Last 200 market sessions based on the most recent close',
    indicatorTitle: 'Indicator Lines',
    indicatorSubtitle: 'Trend strength, confidence, and transition risk',
    resultTitle: 'Analysis Result',
    summaryTitle: 'Interpretation',
    snapshotTitle: 'Indicator Snapshot',
    trend: 'Trend',
    strength: 'Trend strength',
    conviction: 'Conviction',
    risk: 'Transition risk',
    confidence: 'Confidence',
    noDataTitle: 'Upload a CSV to start',
    noDataBody: 'Use the desktop downloader to create an analysis-ready CSV, then upload it here.',
    trendStrengthLine: 'Trend strength',
    confidenceLine: 'Confidence',
    riskLine: 'Transition risk',
    lastClose: 'Last close',
    family: 'Direction family',
    tags: 'Signals'
  },
  ko: {
    featureEyebrow: '내장 도구',
    featureTitle: '추세 분석기',
    featureDescription:
      '분석용 OHLCV CSV를 업로드하면 최근 200일 일봉, 보조지표, 현재 추세 판독 결과를 바로 확인할 수 있습니다.',
    featureCta: '도구 열기',
    eyebrow: '도구 / 주식 추세',
    title: '추세 분석기',
    description:
      '데스크톱 다운로더가 만든 일봉 OHLCV CSV를 업로드하면 서버에서 한 번만 분석하고, 차트용 payload만 돌려준 뒤 업로드 파일은 바로 폐기합니다.',
    tickerLabel: '티커 보정값',
    tickerPlaceholder: 'CSV 파일명에 티커가 이미 들어 있으면 비워둬도 됩니다',
    fileLabel: 'OHLCV CSV 파일',
    fileButton: 'CSV 선택',
    fileEmpty: '선택한 파일 없음',
    submit: 'CSV 분석하기',
    processing: '분석 중...',
    privacyNotice: '업로드한 CSV는 한 번만 분석하고 즉시 삭제합니다. 데이터베이스에 계속 저장하지 않습니다.',
    downloadTitle: '데스크톱 다운로더',
    downloadBody: '독립 실행 앱으로 로컬 CSV를 만든 뒤 이 화면에 업로드해서 분석하세요.',
    macDownload: 'macOS 앱',
    windowsDownload: 'Windows 앱',
    repoLink: '소스 레포',
    csvTitle: '기대하는 CSV 컬럼',
    csvBody: '필수: date, open, high, low, close, volume. 권장: symbol, adj_close.',
    csvHint: '200개 세션 차트와 워밍업 지표를 위해 데스크톱 다운로더는 최근 260거래일 안팎을 저장하는 것을 권장합니다.',
    activeTicker: '선택한 티커',
    fileStatus: '현재 파일',
    asOf: '기준일',
    window: '구간',
    chartTitle: '일봉 캔들 차트',
    chartSubtitle: '최근 장 마감일 기준 과거 200개 세션',
    indicatorTitle: '보조지표 그래프',
    indicatorSubtitle: '추세 강도, 신뢰도, 전환 위험',
    resultTitle: '분석 결과',
    summaryTitle: '해석',
    snapshotTitle: '지표 스냅샷',
    trend: '현재 추세',
    strength: '추세 강도',
    conviction: '추세 확신도',
    risk: '전환 위험',
    confidence: '신뢰도',
    noDataTitle: 'CSV를 업로드하면 결과가 나옵니다',
    noDataBody: '데스크톱 다운로더로 분석용 CSV를 만든 뒤 이 화면에 업로드하세요.',
    trendStrengthLine: '추세 강도',
    confidenceLine: '신뢰도',
    riskLine: '전환 위험',
    lastClose: '최근 종가',
    family: '방향 계열',
    tags: '신호'
  }
} as const;

function normalizeTicker(value: string): string {
  return String(value || '')
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9.\-_]/g, '');
}

function formatDate(value: string | null | undefined, lang: SiteLang): string {
  if (!value) return '-';
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) return value;
  return new Date(parsed).toLocaleDateString(lang === 'ko' ? 'ko-KR' : 'en-US');
}

function formatNumber(value: number | null | undefined, lang: SiteLang, digits = 2): string {
  if (!Number.isFinite(Number(value))) return '-';
  return new Intl.NumberFormat(lang === 'ko' ? 'ko-KR' : 'en-US', {
    minimumFractionDigits: 0,
    maximumFractionDigits: digits
  }).format(Number(value || 0));
}

function formatScore(value: number, lang: SiteLang): string {
  return formatNumber(value, lang, 1);
}

function titleCase(value: string): string {
  return String(value || '')
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((chunk) => chunk.charAt(0).toUpperCase() + chunk.slice(1))
    .join(' ');
}

function scoreTone(value: number): 'low' | 'mid' | 'high' {
  if (value >= 66) return 'high';
  if (value >= 33) return 'mid';
  return 'low';
}

function buildLinePath(values: number[], width: number, height: number, padding: number): string {
  const innerWidth = width - padding * 2;
  const innerHeight = height - padding * 2;
  const safeValues = values.length > 0 ? values : [0];
  const min = Math.min(...safeValues, 0);
  const max = Math.max(...safeValues, 100);
  const span = max - min || 1;

  return safeValues
    .map((value, index) => {
      const x = padding + (innerWidth * index) / Math.max(safeValues.length - 1, 1);
      const y = padding + innerHeight - ((value - min) / span) * innerHeight;
      return `${index === 0 ? 'M' : 'L'} ${x.toFixed(2)} ${y.toFixed(2)}`;
    })
    .join(' ');
}

function buildChartTicks(candles: TrendCandle[]) {
  const midpoint = Math.floor(candles.length / 2);
  return [candles[0]?.date || '', candles[midpoint]?.date || '', candles[candles.length - 1]?.date || ''];
}

function CandlestickChart({ candles, lang }: { candles: TrendCandle[]; lang: SiteLang }) {
  const width = 1040;
  const height = 420;
  const padding = { top: 20, right: 20, bottom: 30, left: 54 };
  const plotWidth = width - padding.left - padding.right;
  const plotHeight = height - padding.top - padding.bottom;
  const highs = candles.map((item) => item.high);
  const lows = candles.map((item) => item.low);
  const maxPrice = Math.max(...highs);
  const minPrice = Math.min(...lows);
  const priceSpan = Math.max(maxPrice - minPrice, 1);
  const stepX = plotWidth / Math.max(candles.length, 1);
  const bodyWidth = Math.max(2, Math.min(5, stepX * 0.56));
  const ticks = buildChartTicks(candles);

  const scaleY = (price: number) => padding.top + ((maxPrice - price) / priceSpan) * plotHeight;

  return (
    <div className="trend-tool-chart">
      <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={lang === 'ko' ? '최근 200일 캔들 차트' : 'Last 200-session candlestick chart'}>
        <rect x="0" y="0" width={width} height={height} rx="20" fill="#fffdf6" />
        {[0, 0.25, 0.5, 0.75, 1].map((ratio) => {
          const y = padding.top + plotHeight * ratio;
          const value = maxPrice - priceSpan * ratio;
          return (
            <g key={`price-grid-${ratio}`}>
              <line x1={padding.left} y1={y} x2={width - padding.right} y2={y} stroke="#d9d2bf" strokeDasharray="4 6" />
              <text x={padding.left - 10} y={y + 4} textAnchor="end" fontSize="11" fill="#5a5342">
                {formatNumber(value, lang, 1)}
              </text>
            </g>
          );
        })}

        {candles.map((candle, index) => {
          const centerX = padding.left + stepX * index + stepX / 2;
          const openY = scaleY(candle.open);
          const closeY = scaleY(candle.close);
          const highY = scaleY(candle.high);
          const lowY = scaleY(candle.low);
          const rising = candle.close >= candle.open;
          const bodyY = Math.min(openY, closeY);
          const bodyHeight = Math.max(Math.abs(closeY - openY), 1.5);
          const bodyColor = rising ? '#174f43' : '#9d2f36';

          return (
            <g key={`candle-${candle.date}`}>
              <line x1={centerX} y1={highY} x2={centerX} y2={lowY} stroke={bodyColor} strokeWidth="1.2" />
              <rect
                x={centerX - bodyWidth / 2}
                y={bodyY}
                width={bodyWidth}
                height={bodyHeight}
                rx="1"
                fill={rising ? '#d6ede5' : '#f6d7d7'}
                stroke={bodyColor}
                strokeWidth="1"
              />
            </g>
          );
        })}

        {ticks.map((tick, index) => (
          <text
            key={`date-tick-${tick}-${index}`}
            x={index === 0 ? padding.left : index === 1 ? width / 2 : width - padding.right}
            y={height - 8}
            textAnchor={index === 0 ? 'start' : index === 1 ? 'middle' : 'end'}
            fontSize="11"
            fill="#5a5342"
          >
            {formatDate(tick, lang)}
          </text>
        ))}
      </svg>
    </div>
  );
}

function IndicatorChart({ candles, lang }: { candles: TrendCandle[]; lang: SiteLang }) {
  const width = 1040;
  const height = 240;
  const padding = 26;
  const trendValues = candles.map((item) => item.trend_strength_score);
  const confidenceValues = candles.map((item) => item.confidence_score);
  const riskValues = candles.map((item) => item.transition_risk_score);
  const ticks = buildChartTicks(candles);

  return (
    <div className="trend-tool-chart">
      <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={lang === 'ko' ? '보조지표 라인 차트' : 'Indicator line chart'}>
        <rect x="0" y="0" width={width} height={height} rx="20" fill="#f8f8f8" />
        {[0, 25, 50, 75, 100].map((value) => {
          const y = padding + ((100 - value) / 100) * (height - padding * 2);
          return (
            <g key={`indicator-grid-${value}`}>
              <line x1={padding} y1={y} x2={width - padding} y2={y} stroke="#d7d7d7" strokeDasharray="4 6" />
              <text x={padding - 8} y={y + 4} textAnchor="end" fontSize="11" fill="#575757">
                {value}
              </text>
            </g>
          );
        })}

        <path d={buildLinePath(trendValues, width, height, padding)} fill="none" stroke="#0f766e" strokeWidth="2.5" />
        <path d={buildLinePath(confidenceValues, width, height, padding)} fill="none" stroke="#1d4ed8" strokeWidth="2.5" />
        <path d={buildLinePath(riskValues, width, height, padding)} fill="none" stroke="#d97706" strokeWidth="2.5" />

        {ticks.map((tick, index) => (
          <text
            key={`indicator-tick-${tick}-${index}`}
            x={index === 0 ? padding : index === 1 ? width / 2 : width - padding}
            y={height - 8}
            textAnchor={index === 0 ? 'start' : index === 1 ? 'middle' : 'end'}
            fontSize="11"
            fill="#575757"
          >
            {formatDate(tick, lang)}
          </text>
        ))}
      </svg>
    </div>
  );
}

function fileNameOrFallback(file: File | null, fallback: string) {
  return file?.name || fallback;
}

export function TrendAnalyzerFeatureCard({ lang }: { lang: SiteLang }) {
  const copy = TOOL_COPY[lang];

  return (
    <section className="tool-feature-card" aria-label={copy.featureTitle}>
      <div className="tool-feature-card__body">
        <p className="tool-feature-card__eyebrow">{copy.featureEyebrow}</p>
        <h2>{copy.featureTitle}</h2>
        <p>{copy.featureDescription}</p>
      </div>
      <Link className="tool-feature-card__link" to={`/${lang}/tools/${TREND_TOOL_SLUG}/`}>
        {copy.featureCta}
      </Link>
    </section>
  );
}

export function TrendAnalyzerToolScreen({ lang }: { lang: SiteLang }) {
  const copy = TOOL_COPY[lang];
  const [tickerInput, setTickerInput] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [selectedTicker, setSelectedTicker] = useState('');
  const [payload, setPayload] = useState<TrendPayload | null>(null);
  const [error, setError] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const candles = payload?.chart_200d?.candles || [];
  const indicatorSnapshot = payload?.indicator_snapshot || {};
  const activeTicker = payload?.meta?.ticker || selectedTicker || '-';
  const fileLabel = fileNameOrFallback(selectedFile, copy.fileEmpty);

  const overviewItems = payload
    ? [
        { label: copy.trend, value: lang === 'ko' ? payload.current_state.trend_state_label_ko : titleCase(payload.current_state.trend_state_label) },
        { label: copy.strength, value: formatScore(payload.current_state.trend_strength_score, lang), tone: scoreTone(payload.current_state.trend_strength_score) },
        { label: copy.conviction, value: formatScore(payload.current_state.trend_conviction_score, lang), tone: scoreTone(payload.current_state.trend_conviction_score) },
        { label: copy.risk, value: formatScore(payload.current_state.transition_risk_score, lang), tone: scoreTone(100 - payload.current_state.transition_risk_score) },
        { label: copy.confidence, value: formatScore(payload.current_state.confidence_score, lang), tone: scoreTone(payload.current_state.confidence_score) }
      ]
    : [];

  const snapshotItems = [
    { label: copy.lastClose, value: indicatorSnapshot.close },
    { label: 'EMA 20', value: indicatorSnapshot.ema20 },
    { label: 'EMA 50', value: indicatorSnapshot.ema50 },
    { label: 'SMA 200', value: indicatorSnapshot.sma200 },
    { label: 'RSI', value: indicatorSnapshot.rsi },
    { label: 'MACD Hist', value: indicatorSnapshot.macd_hist },
    { label: 'ATR %', value: indicatorSnapshot.atr_pct },
    { label: 'ADX', value: indicatorSnapshot.adx }
  ].filter((item) => Number.isFinite(item.value));

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextFile = event.target.files?.[0] || null;
    setSelectedFile(nextFile);
    setError('');
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!selectedFile) {
      setError(lang === 'ko' ? '분석할 CSV 파일을 먼저 선택하세요.' : 'Choose a CSV file to analyze first.');
      return;
    }

    const normalizedTicker = normalizeTicker(tickerInput);
    setIsAnalyzing(true);
    setError('');
    setSelectedTicker(normalizedTicker);

    try {
      const response = await analyzeTrendCsv(selectedFile, normalizedTicker || undefined);
      setPayload(response.payload);
    } catch (analysisError) {
      setPayload(null);
      setError(analysisError instanceof Error ? analysisError.message : lang === 'ko' ? '분석에 실패했습니다.' : 'Analysis failed.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <section className="page-section trend-tool-page">
      <div className="container">
        <div className="trend-tool-shell">
          <header className="trend-tool-head">
            <p className="trend-tool-head__eyebrow">{copy.eyebrow}</p>
            <h1>{copy.title}</h1>
            <p>{copy.description}</p>
          </header>

          <section className="trend-tool-panel trend-tool-panel--info">
            <div className="trend-tool-panel__head">
              <div>
                <h2>{copy.downloadTitle}</h2>
                <p>{copy.downloadBody}</p>
              </div>
            </div>
            <div className="trend-tool-downloads">
              <a className="trend-tool-downloads__link" href={TREND_FETCHER_MAC_URL} target="_blank" rel="noreferrer">
                {copy.macDownload}
              </a>
              <a className="trend-tool-downloads__link" href={TREND_FETCHER_WINDOWS_URL} target="_blank" rel="noreferrer">
                {copy.windowsDownload}
              </a>
              <a className="trend-tool-downloads__link trend-tool-downloads__link--ghost" href={TREND_FETCHER_REPO_URL} target="_blank" rel="noreferrer">
                {copy.repoLink}
              </a>
            </div>
          </section>

          <form className="trend-tool-form" onSubmit={handleSubmit}>
            <label className="trend-tool-form__field">
              <span>{copy.tickerLabel}</span>
              <div className="trend-tool-form__controls">
                <input
                  value={tickerInput}
                  onChange={(event) => setTickerInput(event.target.value)}
                  placeholder={copy.tickerPlaceholder}
                  autoComplete="off"
                  autoCapitalize="characters"
                  spellCheck={false}
                />
              </div>
            </label>

            <label className="trend-tool-form__field">
              <span>{copy.fileLabel}</span>
              <div className="trend-tool-upload-row">
                <label className="trend-tool-file-button">
                  <input type="file" accept=".csv,text/csv" onChange={handleFileChange} />
                  <span>{copy.fileButton}</span>
                </label>
                <span className="trend-tool-file-name">{fileLabel}</span>
              </div>
            </label>

            <div className="trend-tool-form__footer">
              <button type="submit" disabled={isAnalyzing}>
                {isAnalyzing ? copy.processing : copy.submit}
              </button>
              <p className="trend-tool-form__note">{copy.privacyNotice}</p>
            </div>

            {error ? <p className="trend-tool-form__error">{error}</p> : null}
          </form>

          <section className="trend-tool-panel trend-tool-panel--info">
            <div className="trend-tool-panel__head">
              <div>
                <h2>{copy.csvTitle}</h2>
                <p>{copy.csvBody}</p>
              </div>
            </div>
            <p className="trend-tool-summary">{copy.csvHint}</p>
          </section>

          <div className="trend-tool-status">
            <span>
              {copy.activeTicker}: <strong>{activeTicker}</strong>
            </span>
            <span>
              {copy.fileStatus}: <strong>{fileLabel}</strong>
            </span>
            {payload ? (
              <>
                <span>
                  {copy.asOf}: <strong>{formatDate(payload.meta.as_of_date, lang)}</strong>
                </span>
                <span>
                  {copy.window}: <strong>{payload.meta.window_bars} bars</strong>
                </span>
                {payload.meta.best_direction_family ? (
                  <span>
                    {copy.family}: <strong>{titleCase(payload.meta.best_direction_family)}</strong>
                  </span>
                ) : null}
              </>
            ) : null}
          </div>

          {payload ? (
            <>
              <div className="trend-tool-panel-grid">
                <section className="trend-tool-panel">
                  <div className="trend-tool-panel__head">
                    <div>
                      <h2>{copy.chartTitle}</h2>
                      <p>{copy.chartSubtitle}</p>
                    </div>
                  </div>
                  <CandlestickChart candles={candles} lang={lang} />
                </section>

                <section className="trend-tool-panel">
                  <div className="trend-tool-panel__head">
                    <div>
                      <h2>{copy.indicatorTitle}</h2>
                      <p>{copy.indicatorSubtitle}</p>
                    </div>
                    <div className="trend-tool-legend">
                      <span className="trend-tool-legend__item trend-tool-legend__item--teal">{copy.trendStrengthLine}</span>
                      <span className="trend-tool-legend__item trend-tool-legend__item--blue">{copy.confidenceLine}</span>
                      <span className="trend-tool-legend__item trend-tool-legend__item--amber">{copy.riskLine}</span>
                    </div>
                  </div>
                  <IndicatorChart candles={candles} lang={lang} />
                </section>
              </div>

              <section className="trend-tool-result">
                <div className="trend-tool-result__head">
                  <h2>{copy.resultTitle}</h2>
                </div>

                <div className="trend-tool-score-grid">
                  {overviewItems.map((item) => (
                    <article
                      key={`overview-${item.label}`}
                      className={`trend-tool-score-card${item.tone ? ` trend-tool-score-card--${item.tone}` : ''}`}
                    >
                      <span>{item.label}</span>
                      <strong>{item.value}</strong>
                    </article>
                  ))}
                </div>

                <div className="trend-tool-analysis-grid">
                  <article className="trend-tool-panel">
                    <div className="trend-tool-panel__head">
                      <div>
                        <h2>{copy.summaryTitle}</h2>
                        <p>{payload.current_state.summary_text}</p>
                      </div>
                    </div>
                    <p className="trend-tool-summary">
                      {lang === 'ko' ? payload.current_state.interpretation_text_ko : payload.current_state.summary_text}
                    </p>
                    {Array.isArray(payload.current_state.tags) && payload.current_state.tags.length > 0 ? (
                      <p className="trend-tool-tag-line">
                        {copy.tags}: <strong>{payload.current_state.tags.join(', ')}</strong>
                      </p>
                    ) : null}
                  </article>

                  <article className="trend-tool-panel">
                    <div className="trend-tool-panel__head">
                      <div>
                        <h2>{copy.snapshotTitle}</h2>
                        <p>{payload.meta.ticker}</p>
                      </div>
                    </div>
                    <dl className="trend-tool-metric-list">
                      {snapshotItems.map((item) => (
                        <div key={`snapshot-${item.label}`}>
                          <dt>{item.label}</dt>
                          <dd>{formatNumber(Number(item.value), lang, 2)}</dd>
                        </div>
                      ))}
                    </dl>
                  </article>
                </div>
              </section>
            </>
          ) : (
            <section className="trend-tool-panel trend-tool-panel--empty">
              <h2>{copy.noDataTitle}</h2>
              <p>{copy.noDataBody}</p>
            </section>
          )}
        </div>
      </div>
    </section>
  );
}
